### PR TITLE
Test private fields as accessors

### PR DESCRIPTION
**Pull request by rricard**
This is a followup to https://github.com/terser/terser/pull/913. @robpalme suggested that we test accessors as we've seen other projects handle them sub-optimally: thankfully terser seems to be ok with them!

### CODE REVIEW

**Comment by fabiosantoscode** [comment]
Oh cool!

I didn't even realize private accessors were a thing :sweat_smile: 

I'm going to make sure they are properly turned into mozilla AST, and release a beta on npm.

**Comment by fabiosantoscode** [comment]
Actually, the support wasn't there at all, and the tests were trolling you :)

Terser wasn't picking up on the fact that it was private and the `#` was stripped both from `input` and `expect` (this is why `expect_exact` exists).

I'm adding support for private get/set right now.

**Comment by rricard** [comment]
> Actually, the support wasn't there at all, and the tests were trolling you :)

Oh yea it is not the first time I get fooled by them!

> I'm adding support for private get/set right now.

 Let me know if you want me to look at it as well.

**Comment by fabiosantoscode** [comment]
Go ahead :) It's been released on npm too, under the version 5.6.0-beta

I'll be having a second look myself but I'm moderately confident in it.

**Comment by rricard** [comment]
We plan on trying it internally soon-ish but terser is not the only dep we need to consider in our build pipeline, will give you feedback once I get to try it! The first thing that I can try is to see if the feature doesn't change the code we have that is not using private fields.

**Comment by fabiosantoscode** [comment]
That still helps :)

I looked at the AST and now that classes are so different, I'm considering separating ObjectProperty from ClassProperty entirely. There's lots of checks and is_class going on!

**Comment by rricard** [comment]
I can confirm that all of the code we have end up being strictly equivalent between `5.5.1` and `5.6.0-beta`

**Pull request merged**
