### PR TITLE
Fix regex parsing in CLI

### LINKED ISSUE #483: CLI: `--mangle-props regex=/regex/` is broken
**Bug report or Feature request?**

**Version (complete output of `terser -V` or specific git commit)**
4.3.4

**Complete CLI command or `minify()` options used**
```bash
$ npx terser --mangle-props regex=/^_/ temp.js
```

(just like provided in the README, using Bash shell)

**`terser` input**

```js
function f(obj) {
	obj._somePrivateProperty = false;
	obj.nonPrivateProperty = true;
}
```

**`terser` output or error**

```js
function f(f){f.t=false;f.u=true}
```

**Expected result**
```js
function f(f){f.t=false;f.nonPrivateProperty=true}
```

### PR DESCRIPTION
**Pull request by RReverser**
Make sure that regex nodes are correctly parsed into RegExp option as per README.

Fixes #483.

### CODE REVIEW

**Comment by RReverser** [comment]
I couldn't find any CLI tests to add this to, so I guess examples from README would suffice.

Before this change https://github.com/terser/terser/blob/f965ba387d9851f9b6c394b3134e587e180871d8/README.md#L304-L310

transformed not to the documented output, but to:

```js
var x={o:(0,3),t:1,i:function(){return this.t+this.o},s:2};console.log(x.i());
```

while now it transforms to:

```js
var x={o:(0,3),t:1,calc:function(){return this.t+this.o},i:2};console.log(x.calc());
```

**Comment by RReverser** [comment]
Failing tests are not relevant to this PR and are currently failing on master too.

**Comment by RReverser** [comment]
Btw, `o:(0,3)` is suspicious on its own - since both expressions are pure, this should compress to just `3`.

**Comment by kzc** [comment]
This was a recent regression.

```
$ node_modules/.bin/terser -V
terser 4.3.2

$ node_modules/.bin/terser example.js -c -m --mangle-props regex=/_$/
var x={o:(0,3),t:1,calc:function(){return this.t+this.o},i:2};console.log(x.calc());
```

Could you please update the README examples to match this PR's output and add a mocha CLI test in `test/mocha/cli.js` to prevent a future regression of this nature?

> o:(0,3) is suspicious on its own

See `passes` which is documented in the `compress` options. Probably should update the README example with it as well.

```
$ node_modules/.bin/terser example.js -c passes=2 -m --mangle-props regex=/_$/
var x={o:3,t:1,calc:function(){return this.t+this.o},i:2};console.log(x.calc());
```

**Comment by RReverser** [comment]
> Could you please update the README examples to match this PR's output and add a mocha CLI test in `test/mocha/cli.js` to prevent a future regression of this nature?

Ah, that's the one I couldn't find. Btw, what's the difference between `cli.js` and `cli-2.js`? Should I definitely add to the first one?

> Probably should update the README example with it as well.

Do you mean in addition to existing example, or instead of?

**Comment by kzc** [comment]
I don't think it matters much regarding where the new CLI is put.

> Do you mean in addition to existing example, or instead of?

Instead of.  Just replace the command and output to match whatever the PR produces.

The most recent commit on master fails tests. You could rebase this PR to a prior commit for test purposes until the maintainer can address that. It wouldn't affect merging in any case.

**Comment by RReverser** [comment]
> The most recent commit on master fails tests.

Yeah that's what I mentioned above. I'd wait for it to be fixed either way.

**Comment by kzc** [comment]
I did a quick scan to see if other CLI regexes do not have test coverage and might also be broken. It appears that `--keep-fnames` and `--keep-classnames` don't have optional regex support in the CLI even though the underlying minify API supports it for `keep_fnames` and `keep_classnames` respectively.  Since you're already in the same source file, there'd be good karma for you if you address that as well:

https://github.com/terser/terser/blob/8a936fabb3cbb5d5a77c07dee283713a769c289d/bin/terser#L107-L112

**Comment by RReverser** [comment]
I already added `keep_fnames` just as one more example of a property that supports regexp in tests.

> don't have optional regex support in the CLI even though the underlying minify API

They do, but only via `-m keep_fnames=/regex/` syntax.

I suppose there are reasons for that, and I don't really want to derail this PR into implementing a new feature/syntax, but rather keep a limited scope of fixing a specific regression.

**Comment by kzc** [comment]
Fair enough. LGTM.

**Comment by fabiosantoscode** [comment]
Hey there! Thanks for fixing this so quickly!

This bug was entirely my fault, I decided that it was a bit annoying that AST_RegExp had an actual RegExp as its value, and not all node versions were compatible with the latest and greatest in RegExp syntax. I overlooked parsing such CLI options.

**Comment by RReverser** [comment]
> not all node versions were compatible with the latest and greatest in RegExp syntax

Oh that's understandable. We made similar decision in ESTree some time (3 years?) ago, although to preserve backward compatibility we added source+flags object as a new field instead of changing the existing value.

Either way, glad this is fixed now.

**Comment by RReverser** [comment]
@fabiosantoscode Are you planning to make a patch release anytime soon, btw?

**Comment by fabiosantoscode** [comment]
Yes :) in a few hours I'll do that.

**Pull request merged**
