### PR TITLE
Replace non-inclusive "whitelist" term with "allow"

### PR DESCRIPTION
**Pull request by wojtekmaj**

### CODE REVIEW

**Comment by Conduitry** [comment]
image

Truly the easiest way to make the world a better place.

This is dumb.

**Comment by wojtekmaj** [comment]
If you look closely, you'll find 7,258 contributions on my profile that were _not_ connected in any way to making code racially neutral. From 2020. And 6,856 from 2019.

Feel free to browse and maybe you'll find something that suits you more.

**Comment by L2jLiga** [comment]
Don't like this trend 😶😐

**Comment by fabiosantoscode** [comment]
Hey there!

Thanks for having a look.

I've been putting off renaming the main branch as well.

To be clear, I don't consider Terser to have any political inclinations, but to me making sure nobody feels unwelcome on account of who they are is not a political matter at all.

And hey, if it turns out this really doesn't matter, worst case scenario I lost about 20 minutes to it.

**Pull request merged**
