### PR TITLE
fix: fix incorrect node engine semver versions

### PR DESCRIPTION
**Pull request by alan-agius4**
Currently this shows error terser@5.3.6: The engine "node" is incompatible with this module. Expected version "^10.0.0,^11.0.0,^12.0.0,>=14.0.0". Got "12.18.4"

Closes: https://github.com/terser/terser/issues/854

### CODE REVIEW

**Review by artsiomr — APPROVED** [review]

**Comment by LokeshNSF** [comment]
I think the review is approved. Can someone merge this PR.

**Comment by NickKaramoff** [comment]
This also seems to fix #856 and #858

Tagging @fabiosantoscode @alexlamsl since they might not get notified about the PR since they're not assigned

**Review by NickKaramoff — APPROVED** [review]

**Review by s-dupuis — APPROVED** [review]

**Review by PhilippMeissner — APPROVED** [review]

**Review by dumavit — APPROVED** [review]

**Comment by dumavit** [comment]
please merge

**Review by melnikovic — APPROVED** [review]

**Comment by fabiosantoscode** [comment]
Hello there! Thank you, let's get this released!

**Comment by mauroporras** [comment]
This is a good explanation: https://github.com/terser/terser/pull/857#issue-505891464

**Pull request merged**
