### PR TITLE
disabled binary ops optimizations for BigInt

### LINKED ISSUE #546: BigInt turned into scientific notation numbers
**Bug**

**Version: 4.4.0**

**Complete CLI command: `terser --compress --mangle`**

**`terser` input**

```
const a = 10n ** 6n;
```

**`terser` output or error**

```
const a = 1e6;
```

**Expected result**

```
const a = 1000000n;
```

As you can tell, the plugin does not respect `BigInt` and turns them into regular numbers which are not compatible with `BigInt` arithmetic.

### PR DESCRIPTION
**Pull request by L2jLiga**
optimizations for AST_Binary will prevented if one of operands is BigInt

Closes #546

### CODE REVIEW

**Comment by L2jLiga** [comment]
Functional tests fails, idk why, seems like minify finished with error for `computer-science` tests, I've created PR where I added message to assert: https://github.com/terser/terser-functional-tests/pull/95

**Comment by L2jLiga** [comment]
Another option is to drop support `node < 10.4.0` - then we can do operations with BigInt natively as far as node >= 10.4.0 supports BigInt

**Comment by fabiosantoscode** [comment]
Sorry @L2jLiga I didn't notice this PR. The fix is deeper than this, and it involves disabling def_eval for AST_BigInt entirely. But I am stealing your test though :)

**Comment by L2jLiga** [comment]
Good luck, man! :)

**Comment by fabiosantoscode** [comment]
It's fixed @L2jLiga

**Pull request closed without merging**
