### PR TITLE
add minifySync

### PR DESCRIPTION
**Pull request by milahu**
please deliver us from issue #801 

test?

```js
const terser = require('terser');
const cfg = {};
const inn = `
  let f = (a) => {
    console.log('minify me');
  };
  f(1);
`;

const resSync = terser.minifySync(inn, cfg);
const resAsync = terser.minify(inn, cfg);

function assert(cond) {
  console.log(cond ? 'pass' : 'fail');
}

assert(resSync.constructor.name == 'Object');
assert(resAsync.constructor.name == 'Promise');

resAsync.then((value) => {
  assert(value.code == resSync.code);
});
```

as alternative, we could patch the bundle file, see [ds300/patch-package](https://github.com/ds300/patch-package)
but then the sourcemap is wrong

```diff
--- a/dist/bundle.min.js	2020-09-05 08:21:00.546912714 +0200
+++ b/dist/bundle.min.js	2020-09-05 08:21:15.143652480 +0200
@@ -25914,6 +25914,10 @@
 }
 
 async function minify(files, options) {
+    return minifySync(files, options);
+}
+
+function minifySync(files, options) {
     options = defaults(options, {
         compress: {},
         ecma: undefined,
@@ -26605,6 +26609,7 @@
 exports._default_options = _default_options;
 exports._run_cli = run_cli;
 exports.minify = minify;
+exports.minifySync = minifySync;
 
 })));
 //# sourceMappingURL=bundle.min.js.map
```

### CODE REVIEW

**Comment by fabiosantoscode** [comment]
This won't work when source-map is updated. The new version is written in WASM and will require async.

Currently it's async for no reason other than to only bump one major version, instead of bumping multiple versions in a short period of time. Updating source-map should be really simple though and it will break this fix.

Thanks for sending this anyway!

**Comment by milahu** [comment]
no, you got me wrong

i want to keep the existing `async minify()` interface (async is default in modern javascript)
and only add the `minifySync()` interface, so users can have 'the best of both worlds'

this naming is consistent with node APIs like `async fs.readFile()` and `fs.readFileSync()`

only internally the async is a wrapper for the sync function
cos the other way round is much much more expensive (see issue #801)

**Comment by milahu** [comment]
push - whats the problem? cos i dont see one

**Comment by fabiosantoscode** [comment]
The source-map package is async, so every code calling into it is async as well.

I understand that there's no problem with this PR right now, but I'm already in the process of updating source-map, and as soon as I push that work, this won't work anymore.

**Comment by milahu** [comment]
> as soon as I push that work, this won't work anymore.

why??

terser can have both interfaces, async and sync

**Comment by fabiosantoscode** [comment]
But source-map only has an async interface from now on.

**Comment by milahu** [comment]
NOW i get it .... thanks for your patience .__.

this means i will have to fork terser to use the old source-map 0.6
or use [a hack](https://github.com/mozilla/source-map/pull/369) to load the WASM binary in sync

looks like source-map 0.7 will be async only, since the WASM init is 'usually' async

close accepted : D

**Pull request closed without merging**
