### PR TITLE
add ls-lint

### PR DESCRIPTION
**Pull request by loeffel-io**
Hey @fabiosantoscode,

added [ls-lint](https://github.com/loeffel-io/ls-lint) as discussed. 

Just let me know if you are happy with the current configuration: 

```yaml
ls:
    '{lib,tools,test}':
        .js: kebab-case
        .ts: kebab-case
        .d.ts: kebab-case
        .html: kebab-case
        .json: kebab-case

ignore:
    - test/input
    - test/compress
    - lib/utils/first_in_statement.js
```

Merge of the [terser-functional-tests pr](https://github.com/terser/terser-functional-tests/pull/103/files) is required

### CODE REVIEW

**Comment by fabiosantoscode** [comment]
This looks great Lucas!

Would be cool if there was a `ls-lint --fix` which renamed files :)

Anyway, please push an updated package-lock.json so the build runs correctly and I can merge!

**Comment by loeffel-io** [comment]
@fabiosantoscode 

Thanks!

`ls-lint --fix` would be awesome but to support all kind of programming languages could be a mess - but could be a feature in the future :) 

 updated the package-lock.json 

the merge of the [terser functional tests pr](https://github.com/terser/terser-functional-tests/pull/103) is required first, isn`t it?

**Comment by loeffel-io** [comment]
ping @fabiosantoscode  ✌️

**Comment by fabiosantoscode** [comment]
Hey there :)

Let's merge this.

The functional-tests repository is for running tests against minified code. So far it runs the React tests, acorn tests, eslint tests and a few more. It makes sure Terser with default settings doesn't produce code that works differently.

**Comment by loeffel-io** [comment]
Hey @fabiosantoscode, 

alright, thanks for the explanation! 💯

**Comment by loeffel-io** [comment]
Just ping me if you need anything

**Pull request merged**
