### PR TITLE
WIP: Added support for class properties and static class properties

### LINKED ISSUE #303: Parser support for Public Class Fields
**Feature request**

This is a proposal to add support for [Public Class Fields](https://github.com/tc39/proposal-class-fields) to the Terser parser.
The goal is simply to allow pass-through behavior - no compression or mangling.
The proposed scope is public fields only, as that is what has been shipping in Chrome 72 since January 2019.

The language proposal is currently Stage-3 so I'd like to check if the Terser project is comfortable adding support at this point in time?
The status of other tooling's support for this feature is found [here](https://github.com/tc39/proposal-class-fields/issues/57).
Of note, [Babel](https://babeljs.io/blog/2018/08/27/7.0.0#tc39-proposals-https-githubcom-tc39-proposals-support) and [Acorn](https://github.com/acornjs/acorn-class-fields) have already landed support.
TypeScript support is a [work-in-progress](https://github.com/bloomberg/TypeScript/tree/es-private-fields).

If this proposal is acceptable, we can follow up with PRs to add the feature, unless someone else out there is super keen to contribute this.

### PR DESCRIPTION
**Pull request by L2jLiga**
Closes #303

### CODE REVIEW

**Comment by robpalme** [comment]
Is there anything to do to help this land?

**Comment by fabiosantoscode** [comment]
I've talked to @L2jLiga outside github. This will be pretty complicated due to the fact that after the `=` sign there is a whole new kind of scope. One that has the `this` binding of the instance of the class and is executed once every time the class is instantiated.

Terser needs a bit of a refactor in how it currently deals with scopes because of this ES feature. It's a sad feature to boot, super unintuitive for the reader.

**Comment by fabiosantoscode** [comment]
@L2jLiga I'm taking this over, thanks for starting this out :)

**Comment by robpalme** [comment]
Hell @L2jLiga - thank you for keeping this branch up to date.  Is there any more work needed on this PR? Maybe I could push a few more test cases?

**Comment by L2jLiga** [comment]
@robpalme good question! We've discussed some corner cases which we may face with and according to @fabiosantoscode comment there few things to be done in how terser deals with scope.. :thinking: 
@fabiosantoscode what is left here? As for me all is ok:

*command*: `terser -c passes=3 --toplevel`
*input*:
```javascript
class Foo {
    bar = Symbol("hey-ho");
}

let a = "PASS";
if (new Foo().bar === new Foo().bar) a = "FAIL";

console.log(a); // PASS
```
*output*:
```javascript
class Foo{
  bar=Symbol("hey-ho")
}
let a="PASS";
(new Foo).bar==(new Foo).bar && (a = "FAIL"),

console.log(a); // PASS
```

**Comment by fabiosantoscode** [comment]
Nice test case! Please add it!

I think we can merge this to master after I release the newest terser today. Then we can deal with the following issue:

Static properties may have side effects and might throw even though Terser is assuming that the only thing that might, is the extends clause. So this might affect reduce_vars, side_effects and unused.

Test cases:

```
let x = "FAIL"
class X {
  static _ = (x = "PASS")
}
console.log(x)
```

And

```
let x = "FAIL"
try {
  class X {
    static _ = ima_throw_lol()
  }
} catch(e) {
  x = "PASS"
}
console.log(x)
```

And also

```
let x = "FAIL"
function impure() {
  x = "PASS"
}
class Unused {
  static _ = impure()
}
```

Now that I think of it classes might be inlined into their construction site and break code order if they have impure static values.

```
let x = ""
class Y {
  static _ = (x += "PA")
}
class X {
  static _ = (x += "SS")
}
global.something = [new X(), new Y()]
```

**Comment by fabiosantoscode** [comment]
If we get this right private properties should be even easier. You can only use those fancy "#" symbols in property access. We can make them a new subclass of AST_Symbol to stop existing code from mixing it up with regular object properties and refs.

**Comment by fabiosantoscode** [comment]
Ok, 4.5.0 is out. Adding to master and those tests too. It should be pretty easy to make them pass.

**Pull request merged**
