### PR TITLE
Evaluate some BigInt operations

### PR DESCRIPTION
**Pull request by fabiosantoscode**
Not confident enough to release this right now because handling BigInt can cause a bunch of TypeErrors, both in Terser and output code.

### CODE REVIEW

**Comment by dead-claudia** [comment]
> To do: avoid dividing by zero!

@fabiosantoscode You might be able to get away with a sentinel value (say, a special object or symbol) and using that for a synthetic "not-a-number" value for bigints. That  may be easier to fuse in since it'll require less code motion. Then, in the end, you can render that synthetic value to a single representation like `0n/0n` (along with maybe a compiler warning) to ensure the `TypeError` ultimately gets thrown in the end.

**Comment by fabiosantoscode** [comment]
I think I'll just make `1234n / 0n` transform into itself (simply `return this`). This is way too much of a corner case in my opinion, if someone wrote code that will 100% crash they can afford a couple extra bytes, nobody does this normally

**Comment by fabiosantoscode** [comment]
The TODO was just to avoid Terser itself creating y

**Comment by dead-claudia** [comment]
@fabiosantoscode Fair enough. I was just giving a stray suggestion.

**Pull request merged**
