### PR TITLE
Ensure parent directory exists when using --output on CLI

### LINKED ISSUE #962: Terser returns error if folders, specified in --output parameter are not present in file system
Hello!

**Can't exactly say its a bug or I'm missing something**

**Version: terser 5.6.1**

I run a command:
**npx terser wwwroot/build/js/admin.js --compress typeofs=false --mangle --comments \"/^!/\" --output wwwroot/dist/js/admin.min.js**

Then I get an error:
**Error: ENOENT: no such file or directory, open 'wwwroot/dist/js/admin.min.js'
    at Object.openSync (fs.js:476:3)
    at Object.writeFileSync (fs.js:1467:35)
    at run_cli (C:\Users\Alex\source\repos\x\src\Web\node_modules\terser\dist\bundle.min.js:26901:16)
    at run_cli (C:\Users\Alex\source\repos\x\src\Web\node_modules\terser\dist\bundle.min.js:26782:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'wwwroot/dist/js/admin.min.js'
}**

**Expected result: I expect to see minified file in --output wwwroot/dist/js/admin.min.js**

If I have "dist" folder empty with no subfolders, I get the error.
If I create "js" folder inside "dist" folder, then minified file is create and I get no error.

Am I missing something or terser just does not create output folders by itself?

### PR DESCRIPTION
**Pull request by RyanZim**
Resolves #962

Happy to add tests for this, but I didn't see any existing tests for the `--output` CLI option; am I missing them?

### CODE REVIEW

**Comment by fabiosantoscode** [comment]
Hey there! Thanks for the PR

You could add a test with --output on test/mocha/cli.js. I didn't find an existing one either!

**Comment by RyanZim** [comment]
Finally got around to adding a test for this (sorry for the long wait). Ready for review.

**Review by fabiosantoscode — APPROVED** [review]
looks good, let me look at CI now

**Comment by fabiosantoscode** [comment]
Great, thank you!

**Pull request merged**
