### PR TITLE
Terser for Gulp

### PR DESCRIPTION
**Pull request by brendan8c**
I wrote some code that allows to use the 'terser' plugin in the 'gulp' build.
There is no longer any need to use additional plugins for this.

### CODE REVIEW

**Comment by fabiosantoscode** [comment]
Hello!

Thanks for this. Could you add error handling to this plugin? The minify function throws syntax errors and other failures. Also this should probably be in a RECIPES.md file

**Comment by brendan8c** [comment]
> Привет!
> 
> Спасибо за это. Не могли бы вы добавить в этот плагин обработку ошибок? Функция minify выдает синтаксические ошибки и другие сбои. Также это, вероятно, должно быть в файле RECIPES.md.

Yes, I will try to do it.

**Comment by brendan8c** [comment]
I don't understand where this file (RECIPES.md) is, I did not find it.

**Comment by fabiosantoscode** [comment]
It should be a new file, linked from the README.md. 

I'll make sure it shows up in a new section on terser.org too, there's a script that syncs it with the readme and I'll just need to add the recipes to that script.

**Comment by brendan8c** [comment]
> It should be a new file, linked from the README.md.
> 
> I'll make sure it shows up in a new section on terser.org too, there's a script that syncs it with the readme and I'll just need to add the recipes to that script.

I have never done this and have not found information on the Internet.
Do I need to create a RECIPES.md file in the root of this repo and put what I wrote in the README.md file there?
Please tell us in more detail.

**Comment by fabiosantoscode** [comment]
Yes, do place it in a RECIPES.md. I'll handle the rest

**Comment by brendan8c** [comment]
> Yes, do place it in a RECIPES.md. I'll handle the rest

I did it, I hope everything is correct.
[RECIPES.md](https://github.com/terser/terser/pull/1035)

**Comment by fabiosantoscode** [comment]
Merged in #1035

**Pull request closed without merging**
